function first_function()
{
    try
    {
        print("This is before the function call")
        second_function()
        print("This is after the function call")
    }
    catch (Exception)
    {
        print("This is the first exception handler")
    }
    print("This is after the handler")
}

function second_function()
{
    throw Exception("My exception has a message")
}

function test_function() {
    try {
        print("inside the try")
    }
    finally {
        print('finally after try')
    }
}

first_function()
test_function()